const express=require("express"),multer=require("multer"),fs=require("fs"),path=require("path");
const app=express(),ROOT=__dirname,DB=path.join(ROOT,"data/db.json"),PORT=process.env.PORT||3000;
app.use(express.json({limit:"20mb"})); app.use(express.urlencoded({extended:true})); app.use(express.static(path.join(ROOT,"public"))); app.use("/uploads",express.static(path.join(ROOT,"uploads")));
const read=()=>JSON.parse(fs.readFileSync(DB,"utf8")); const write=d=>fs.writeFileSync(DB,JSON.stringify(d,null,2));
function guard(req,res,next){if(req.header("x-admin-token")!==(process.env.ADMIN_PASSWORD||"change-me-now"))return res.status(401).json({error:"Unauthorized"});next()}
const storage=multer.diskStorage({destination:(r,f,cb)=>cb(null,path.join(ROOT,"uploads",f.mimetype.startsWith("image/")?"images":"videos")),filename:(r,f,cb)=>cb(null,Date.now()+"-"+path.basename(f.originalname).replace(/[^a-zA-Z0-9._-]/g,"-").toLowerCase())});
const upload=multer({storage,limits:{fileSize:8*1024*1024*1024}});
app.get("/api/config",(req,res)=>res.json(read().settings));
app.get("/api/anime",(req,res)=>{let a=read().anime,q=(req.query.q||"").toLowerCase().trim(),g=(req.query.genre||"").toLowerCase().trim();if(q)a=a.filter(x=>[x.title,x.originalTitle,x.englishTitle,...(x.genres||[])].join(" ").toLowerCase().includes(q));if(g)a=a.filter(x=>(x.genres||[]).some(y=>y.toLowerCase()===g));res.json(a)});
app.get("/api/anime/:id",(req,res)=>{const a=read().anime.find(x=>x.id===req.params.id);a?res.json(a):res.status(404).json({error:"Not found"})});
app.post("/api/admin/login",(req,res)=>req.body.password===(process.env.ADMIN_PASSWORD||"change-me-now")?res.json({token:process.env.ADMIN_PASSWORD||"change-me-now"}):res.status(401).json({error:"Құпиясөз қате"}));
app.get("/api/admin/stats",guard,(req,res)=>{const a=read().anime;res.json({anime:a.length,episodes:a.reduce((n,x)=>n+(x.episodesData||[]).length,0),movies:a.filter(x=>x.status==="movie").length,series:a.filter(x=>x.status!=="movie").length})});
app.put("/api/admin/settings",guard,(req,res)=>{const d=read();d.settings={...d.settings,...req.body};write(d);res.json(d.settings)});
app.post("/api/admin/anime",guard,(req,res)=>{const d=read(),title=req.body.title||"Жаңа аниме",id=(req.body.id||title).toString().toLowerCase().trim().replace(/[^a-z0-9а-яёңғүұқөһәі\- ]/gi,"").replace(/\s+/g,"-");const item={id,title,originalTitle:req.body.originalTitle||"",englishTitle:req.body.englishTitle||"",year:+req.body.year||new Date().getFullYear(),status:req.body.status||"series",genres:Array.isArray(req.body.genres)?req.body.genres:String(req.body.genres||"").split(",").map(x=>x.trim()).filter(Boolean),rating:String(req.body.rating||"—"),poster:req.body.poster||"",backdrop:req.body.backdrop||"",description:req.body.description||"",tags:Array.isArray(req.body.tags)?req.body.tags:String(req.body.tags||"").split(",").map(x=>x.trim()).filter(Boolean),episodesData:[],episodes:0};const i=d.anime.findIndex(x=>x.id===id);i>=0?d.anime[i]=item:d.anime.unshift(item);write(d);res.json(item)});
app.delete("/api/admin/anime/:id",guard,(req,res)=>{const d=read(),n=d.anime.length;d.anime=d.anime.filter(x=>x.id!==req.params.id);if(n===d.anime.length)return res.status(404).json({error:"Not found"});write(d);res.json({ok:true})});
app.post("/api/admin/anime/:id/episode",guard,(req,res)=>{const d=read(),a=d.anime.find(x=>x.id===req.params.id);if(!a)return res.status(404).json({error:"Anime not found"});a.episodesData=a.episodesData||[];const number=+req.body.number||a.episodesData.length+1;a.episodesData.push({id:a.id+"-"+Date.now(),number,title:req.body.title||`Серия ${number}`,videoUrl:req.body.videoUrl||"",subtitleUrl:req.body.subtitleUrl||"",audio:req.body.audio||"Original",quality:req.body.quality||"1080p FHD",duration:req.body.duration||"—"});a.episodes=a.episodesData.length;write(d);res.json(a.episodesData.at(-1))});
app.delete("/api/admin/anime/:id/episode/:eid",guard,(req,res)=>{const d=read(),a=d.anime.find(x=>x.id===req.params.id);if(!a)return res.status(404).end();a.episodesData=(a.episodesData||[]).filter(e=>e.id!==req.params.eid);a.episodes=a.episodesData.length;write(d);res.json({ok:true})});
app.post("/api/admin/upload",guard,upload.single("file"),(req,res)=>{if(!req.file)return res.status(400).json({error:"File required"});const folder=req.file.mimetype.startsWith("image/")?"images":"videos";res.json({url:`/uploads/${folder}/${req.file.filename}`})});
app.get("*",(req,res)=>res.sendFile(path.join(ROOT,"public/index.html"))); app.listen(PORT,()=>console.log(`ᑌᑎᔕIᘔ ᗩᑎIᗰE: http://localhost:${PORT}`));
